// ============================================================
// GCSE SPEC DATA — RAM'S EXAM COMMAND CENTER (FIXED 2026)
// Exam dates from Ram's verified timetable.
// Full spec content + correct getDailyRecommendation() for app.js.
// ============================================================

const GCSE_SUBJECTS = {

  // ── MATHS (Edexcel) ───────────────────────────────────────
  maths: {
    name: "Mathematics",
    board: "Edexcel",
    color: "#3b82f6",
    icon: "📐",
    exams: [
      { paper: "Paper 1 (Non-Calc)", date: "2026-05-14", time: "AM" },
      { paper: "Paper 2 (Calc)",     date: "2026-06-03", time: "AM" },
      { paper: "Paper 3 (Calc)",     date: "2026-06-10", time: "AM" },
    ],
    topics: [
      { id: "m1", topic: "Number", points: [
        "Integers, decimals, fractions — place value & ordering",
        "HCF, LCM, prime factorisation",
        "Powers, roots, surds",
        "Standard form (scientific notation)",
        "Percentages — increase/decrease, reverse, compound",
        "Ratio and proportion",
        "Bounds and error intervals",
      ]},
      { id: "m2", topic: "Algebra", points: [
        "Simplifying expressions & expanding brackets",
        "Factorising — common factor, difference of squares, quadratics",
        "Solving linear equations & inequalities",
        "Solving quadratics — factorising, formula, completing the square",
        "Simultaneous equations — substitution & elimination",
        "Sequences — nth term, arithmetic & geometric",
        "Functions — notation, composite, inverse",
        "Algebraic fractions",
        "Proof",
      ]},
      { id: "m3", topic: "Graphs", points: [
        "Coordinates and straight-line graphs (y=mx+c)",
        "Parallel & perpendicular lines",
        "Quadratic, cubic, reciprocal graphs",
        "Exponential and trigonometric graphs",
        "Transformations of graphs",
        "Real-life graphs — distance/time, velocity/time",
        "Gradient of a curve (tangent)",
        "Area under a graph",
      ]},
      { id: "m4", topic: "Ratio, Proportion & Rates", points: [
        "Direct and inverse proportion",
        "Speed, distance, time",
        "Density, mass, volume",
        "Exchange rates & best-buy problems",
        "Percentage problems — simple & compound interest",
      ]},
      { id: "m5", topic: "Geometry & Measures", points: [
        "Angles — parallel lines, polygons, bearings",
        "Properties of 2D shapes",
        "Circle theorems (all 8)",
        "Area and perimeter — all 2D shapes",
        "Volume and surface area — prisms, cylinders, spheres, cones, pyramids",
        "Pythagoras theorem",
        "Trigonometry — SOH CAH TOA, exact values",
        "Sine rule & cosine rule",
        "Vectors",
        "Loci and construction",
        "Congruence and similarity",
        "Transformations — reflection, rotation, translation, enlargement",
      ]},
      { id: "m6", topic: "Probability", points: [
        "Basic probability — scale, outcomes, equally likely",
        "Sample space diagrams & tree diagrams",
        "Venn diagrams",
        "Conditional probability",
        "Mutually exclusive & independent events",
        "Frequency trees",
      ]},
      { id: "m7", topic: "Statistics", points: [
        "Averages — mean, median, mode, range",
        "Frequency tables & grouped data",
        "Cumulative frequency & box plots",
        "Histograms — frequency density",
        "Scatter graphs — correlation, line of best fit",
        "Pie charts & bar charts",
        "Sampling methods",
      ]},
    ],
  },

  // ── FURTHER MATHS (AQA L2) ────────────────────────────────
  furtherMaths: {
    name: "Further Maths (L2)",
    board: "AQA",
    color: "#8b5cf6",
    icon: "∑",
    exams: [
      { paper: "Paper 1", date: "2026-06-08", time: "PM" },
      { paper: "Paper 2", date: "2026-06-15", time: "PM" },
    ],
    topics: [
      { id: "fm1", topic: "Number & Algebra", points: [
        "Factor theorem",
        "Algebraic long division",
        "Simplifying algebraic fractions — complex",
        "Completing the square — all forms",
        "Quadratic inequalities",
        "Simultaneous equations — one quadratic",
        "nth roots and fractional/negative indices",
        "Arithmetic & geometric series — notation",
      ]},
      { id: "fm2", topic: "Coordinate Geometry", points: [
        "Equation of a circle: (x-a)^2+(y-b)^2=r^2",
        "Intersection of a line and circle",
        "Tangent to a circle from a point",
        "Distance between two points in 3D",
      ]},
      { id: "fm3", topic: "Calculus", points: [
        "Differentiation — polynomials",
        "Gradient function, tangents & normals",
        "Stationary points — min/max classification",
        "Integration — polynomials",
        "Definite integration — area under a curve",
        "Area between two curves",
      ]},
      { id: "fm4", topic: "Matrix Algebra", points: [
        "Matrix addition, subtraction, multiplication",
        "2x2 determinant and inverse",
        "Matrix transformations — rotation, reflection, enlargement, shear",
        "Combining transformations using matrices",
        "Solving 2x2 simultaneous equations using matrices",
      ]},
      { id: "fm5", topic: "Trigonometry", points: [
        "Exact values: sin/cos/tan of 30, 45, 60 degrees",
        "Sine rule proof",
        "Cosine rule proof",
        "Area of a triangle = 0.5 ab sinC",
        "Solving trig equations in a given interval",
        "Trig identities: sin^2+cos^2=1, tan=sin/cos",
      ]},
      { id: "fm6", topic: "Functions & Graphs", points: [
        "Domain and range",
        "Inverse functions",
        "Composite functions",
        "Modulus function",
        "Graph transformations — all types",
      ]},
    ],
  },

  // ── BIOLOGY (AQA Triple) ──────────────────────────────────
  biology: {
    name: "Biology",
    board: "AQA Triple",
    color: "#84cc16",
    icon: "🧬",
    exams: [
      { paper: "Paper 1 (Topics 1–4)", date: "2026-05-12", time: "AM" },
      { paper: "Paper 2 (Topics 5–7)", date: "2026-06-08", time: "AM" },
    ],
    topics: [
      { id: "bio1", topic: "Cell Biology ★ Paper 1", points: [
        "Eukaryotic vs prokaryotic cells — size comparison",
        "Animal cell structures: nucleus, cytoplasm, cell membrane, mitochondria, ribosomes",
        "Plant cell structures: cell wall (cellulose), vacuole, chloroplasts, plus above",
        "Cell specialisation — examples: sperm, egg, RBC, nerve cell, root hair, ciliated cell",
        "Microscopy — magnification formula: magnification = image size ÷ actual size",
        "Electron vs light microscope — resolution and magnification comparison",
        "Mitosis: DNA replication → G1/S/G2/M phases → 2 genetically identical diploid cells",
        "Cell cycle and role in growth, repair, asexual reproduction",
        "Stem cells — embryonic (pluripotent), adult (limited), meristems in plants",
        "Therapeutic cloning and ethical issues",
        "Diffusion — net movement from high to low concentration",
        "Osmosis — water potential gradient across partially permeable membrane",
        "Active transport — against concentration gradient, requires ATP",
        "Factors affecting diffusion: surface area, concentration gradient, distance",
        "Required Practical 1 — osmosis in potato/plant tissue (mass change method)",
      ]},
      { id: "bio2", topic: "Organisation ★ Paper 1", points: [
        "Cell → tissue → organ → organ system → organism",
        "Digestive system — organs: mouth, oesophagus, stomach, small/large intestine, liver, pancreas",
        "Digestive enzymes: amylase (starch→sugars), protease (proteins→amino acids), lipase (fats→glycerol+fatty acids)",
        "Enzyme action — lock and key model, active site, enzyme-substrate complex",
        "Effect of pH on enzyme — optimum, denaturation above/below optimum",
        "Effect of temperature on enzyme — rate increases to optimum, then denatures",
        "Required Practical 2 — effect of pH on amylase activity",
        "Bile — produced in liver, stored in gall bladder, emulsifies fats",
        "Heart — 4 chambers (atria/ventricles), valves, pacemaker (SAN), double circulatory system",
        "Coronary heart disease — blocked arteries, stents, statins",
        "Blood vessels — arteries (high pressure, thick walls), veins (valves), capillaries (one cell thick, exchange)",
        "Blood components — RBC (haemoglobin, no nucleus), WBC, platelets, plasma",
        "Plant organisation — leaves (photosynthesis), stems (support/transport), roots (absorption)",
        "Transpiration — water loss through stomata; factors: temp, humidity, wind, light",
        "Translocation — phloem transports dissolved sugars from source to sink",
        "Xylem — water and minerals, dead cells, lignified walls",
        "Stomata and guard cells — control gas exchange and water loss",
        "Cancer — benign (localised) vs malignant (spreads/metastasis); lifestyle risk factors",
      ]},
      { id: "bio3", topic: "Infection & Response ★ Paper 1", points: [
        "Pathogens — bacteria (produce toxins), viruses (live inside cells), fungi, protists",
        "Communicable diseases — spread: direct contact, air, water, vectors",
        "Bacterial: Salmonella (food poisoning), Gonorrhoea (STI)",
        "Viral: measles, HIV/AIDS, tobacco mosaic virus (TMV) in plants",
        "Fungal: rose black spot in plants",
        "Protist: malaria (Plasmodium, spread by Anopheles mosquito)",
        "Non-specific defence — skin (barrier), mucus (traps pathogens), cilia, stomach acid",
        "White blood cells — phagocytosis (engulf/destroy), antibody production, antitoxin production",
        "Specific immune response — lymphocytes produce complementary antibodies to antigens",
        "Vaccination — weakened/dead pathogen → antibody memory → herd immunity",
        "Antibiotics — kill bacteria (not viruses); antibiotic resistance — MRSA",
        "Drug development — discovery, lab testing, clinical trials (Phase 1/2/3), peer review",
        "Painkillers vs antibiotics — treat symptoms vs destroy pathogens",
      ]},
      { id: "bio4", topic: "Bioenergetics ★ Paper 1", points: [
        "Photosynthesis equation: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (requires light energy)",
        "Chlorophyll absorbs light; takes place in chloroplasts",
        "Rate of photosynthesis — limiting factors: light intensity, CO₂ concentration, temperature",
        "Required Practical 3 — effect of light intensity on photosynthesis (pondweed/O₂ bubbles)",
        "Inverse square law: light intensity ∝ 1/d²",
        "Uses of glucose in plants: respiration, cellulose (cell walls), starch (storage), proteins (with nitrates), lipids (seeds)",
        "Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP",
        "Anaerobic respiration in humans: glucose → lactic acid (no O₂, less ATP)",
        "Anaerobic respiration in yeast: glucose → ethanol + CO₂ (fermentation)",
        "Response to exercise — increased heart rate, breathing rate, blood flow to muscles",
        "Oxygen debt — extra O₂ needed after exercise to oxidise lactic acid",
      ]},
      { id: "bio5", topic: "Homeostasis & Response ★ Paper 2", points: [
        "Homeostasis — maintaining a constant internal environment (negative feedback)",
        "Nervous system — CNS (brain + spinal cord) + peripheral nervous system",
        "Neurones: sensory (receptor → CNS), relay (within CNS), motor (CNS → effector)",
        "Synapse — neurotransmitters diffuse across gap; one-way transmission",
        "Reflex arc — receptor → sensory → relay → motor → effector (bypasses brain)",
        "The brain — cerebral cortex (thinking/senses), cerebellum (balance), medulla (breathing/heartbeat)",
        "The eye — cornea, iris, lens (accommodation), retina (rods/cones), optic nerve",
        "Accommodation — ciliary muscles/suspensory ligaments change lens shape",
        "Hormones vs nervous system — slower/longer-lasting vs fast/short-lived",
        "Endocrine system — glands: pituitary (master), thyroid, adrenal, pancreas, ovaries/testes",
        "Blood glucose regulation — insulin (lowers) and glucagon (raises) secreted by pancreas",
        "Diabetes Type 1 (no insulin produced) vs Type 2 (cells don't respond to insulin)",
        "Water and ion balance — kidneys filter blood; nephrons reabsorb glucose and water",
        "Urea production — liver converts excess amino acids to urea",
        "Dialysis and kidney transplant — treatment for kidney failure",
        "Menstrual cycle — FSH (follicle), LH (ovulation), oestrogen, progesterone; negative feedback",
        "Contraception — hormonal vs non-hormonal methods",
        "Fertility treatments — IVF, FSH/LH injections",
        "Thermoregulation — hypothalamus monitors core temperature; vasodilation, vasoconstriction, sweating, shivering",
        "Tropic responses in plants — phototropism (auxin), gravitropism (auxin redistribution)",
      ]},
      { id: "bio6", topic: "Inheritance, Variation & Evolution ★ Paper 2", points: [
        "Meiosis — produces 4 genetically unique haploid gametes (sex cells); reduction division",
        "Meiosis vs mitosis: gametes (haploid) vs body cells (diploid)",
        "DNA structure — double helix; bases: A-T, C-G (complementary base pairing)",
        "Gene — section of DNA coding for a protein (sequence of bases → amino acids)",
        "Genome — entire genetic material of an organism",
        "Alleles — different versions of a gene; dominant vs recessive",
        "Homozygous (AA or aa) vs heterozygous (Aa); genotype vs phenotype",
        "Punnett squares — monohybrid cross; ratios 3:1 (dominant:recessive)",
        "Sex determination — XX (female) vs XY (male)",
        "Inherited disorders: cystic fibrosis (recessive, CFTR gene), polydactyly (dominant)",
        "Variation — genetic (mutations, sexual reproduction) and environmental, or both",
        "Evolution — natural selection: variation → competition → survival of fittest → inherited",
        "Evidence for evolution — fossils, antibiotic resistance, embryology",
        "Darwin's theory vs Lamarck's theory of inheritance of acquired characteristics",
        "Speciation — new species formed when populations become isolated and evolve separately",
        "Selective breeding — humans select organisms with desirable traits over generations",
        "Genetic engineering — inserting a gene from one organism into another; GM crops, insulin",
        "Cloning — tissue culture (plants), embryo transplants, adult cell cloning (Dolly the sheep)",
      ]},
      { id: "bio7", topic: "Ecology ★ Paper 2", points: [
        "Ecosystems — biotic (living) and abiotic (non-living) factors",
        "Abiotic factors: light, temperature, moisture, soil pH, wind speed, CO₂/O₂ levels",
        "Biotic factors: predation, competition, disease, food availability",
        "Adaptations — structural (e.g. thick fur), behavioural (e.g. migration), functional (e.g. hibernation)",
        "Extremophiles — organisms adapted to extreme environments (e.g. high temp, high salt)",
        "Competition — intraspecific (same species) and interspecific (different species)",
        "Predator-prey cycles — predator and prey populations are interdependent",
        "Feeding relationships — food chains and food webs; producer → primary → secondary consumer",
        "Biomass pyramids — energy lost between trophic levels (~90% lost as heat)",
        "Decomposers — bacteria/fungi break down dead organisms; recycle nutrients",
        "The carbon cycle — photosynthesis (removes CO₂), respiration/combustion (releases CO₂)",
        "The water cycle — evaporation, condensation, precipitation, transpiration",
        "The nitrogen cycle — nitrogen fixation, nitrification, denitrification, decomposition",
        "Required Practical 7 — quadrats and transects to measure population size/distribution",
        "Biodiversity — variety of species; importance for ecosystem stability and medicine",
        "Human impacts — deforestation, monoculture, pesticides, climate change, pollution, eutrophication",
        "Conservation — protected areas, captive breeding, seed banks, rewilding",
        "Global warming — CO₂/methane from burning fossil fuels; evidence and effects",
      ]},
    ],
  },

  // ── CHEMISTRY (AQA Triple) ────────────────────────────────
  chemistry: {
    name: "Chemistry",
    board: "AQA Triple",
    color: "#10b981",
    icon: "🧪",
    exams: [
      { paper: "Paper 1 (Topics 1–5)", date: "2026-05-18", time: "AM" },
      { paper: "Paper 2 (Topics 6–10)", date: "2026-06-12", time: "AM" },
    ],
    topics: [
      { id: "ch1", topic: "Atomic Structure & Periodic Table ★ Paper 1", points: [
        "Atomic structure — protons (+, nucleus), neutrons (0, nucleus), electrons (-, shells)",
        "Atomic number = proton number; mass number = protons + neutrons",
        "Relative atomic mass (Ar) — weighted average of isotope masses",
        "Isotopes — same element, different number of neutrons",
        "Electronic configurations — first 20 elements (e.g. Na = 2,8,1)",
        "Development of the periodic table — Mendeleev left gaps, predicted elements",
        "Periods (horizontal) = number of electron shells; Groups (vertical) = valence electrons",
        "Metals (left) vs non-metals (right) — properties comparison",
        "Group 1 — alkali metals: reactivity increases down the group; Li, Na, K reactions with water",
        "Group 7 — halogens: reactivity decreases down; displacement reactions (Cl₂ displaces Br⁻)",
        "Group 0 — noble gases: full outer shells, unreactive",
        "Transition metals — good conductors, high melting points, catalysts, coloured compounds",
      ]},
      { id: "ch2", topic: "Bonding, Structure & Properties ★ Paper 1", points: [
        "Ionic bonding — metal loses electrons to non-metal; giant ionic lattice formed",
        "Ionic compounds — high melting/boiling points; conduct electricity when molten or dissolved",
        "Covalent bonding — non-metals share electrons; simple molecules (low mp/bp)",
        "Giant covalent structures — diamond (hard, high mp, insulator), graphite (layers, conductor), graphene, fullerenes",
        "Metallic bonding — positive ions in sea of delocalised electrons",
        "Metallic properties — conductor, malleable, ductile, high mp (usually)",
        "Properties explained by structure — melting point, conductivity, solubility",
        "Polymer structures — long chains; thermosoftening vs thermosetting",
        "Nanoparticles (1–100 nm) — uses: medicine, cosmetics, electronics; risks: unknown toxicity",
        "Size and surface area — nanoparticles have large surface area to volume ratio",
      ]},
      { id: "ch3", topic: "Quantitative Chemistry ★ Paper 1", points: [
        "Relative formula mass (Mr) — sum of Ar values in formula",
        "Moles: n = mass (g) ÷ Mr",
        "Avogadro's constant: 6.02 × 10²³ particles per mole",
        "Balanced equations — mole ratios from coefficients",
        "Concentration: c = n/V (mol/dm³); 1 dm³ = 1 litre",
        "Reacting masses — use mole ratios from equation",
        "Percentage yield = (actual yield ÷ theoretical yield) × 100",
        "Atom economy = (Mr of desired product ÷ sum of Mr of all products) × 100",
        "Molar volume of gas at RTP = 24 dm³/mol (24,000 cm³/mol)",
        "Required Practical 1 — making a salt by titration",
        "Titration calculations — moles from concentration × volume",
      ]},
      { id: "ch4", topic: "Chemical Changes ★ Paper 1", points: [
        "Reactivity series: K, Na, Li, Ca, Mg, Al, Zn, Fe, Ni, Sn, Pb, H, Cu, Ag, Au",
        "Displacement reactions — more reactive metal displaces less reactive metal from solution",
        "Extraction of metals — electrolysis (Al, Na); carbon reduction (Fe in blast furnace)",
        "Blast furnace — coke, limestone, iron ore; reactions with carbon",
        "Oxidation (lose electrons, gain O) vs reduction (gain electrons, lose O) — OIL RIG",
        "pH scale: 0–14; pH 7 = neutral; below 7 = acid; above 7 = alkali",
        "Neutralisation — acid + alkali → salt + water",
        "Acid + metal → salt + hydrogen; test: squeaky pop with lighted splint",
        "Acid + carbonate → salt + water + CO₂; test: limewater turns milky",
        "Acid + base (metal oxide) → salt + water",
        "Naming salts — HCl → chloride, H₂SO₄ → sulfate, HNO₃ → nitrate",
        "Electrolysis — using electricity to decompose ionic compounds",
        "Products at electrodes: anode (+) → non-metal/oxygen; cathode (–) → metal/hydrogen",
        "Electrolysis of brine — Cl₂ (anode), H₂ (cathode), NaOH (remains in solution)",
        "Half equations for electrode reactions",
      ]},
      { id: "ch5", topic: "Energy Changes ★ Paper 1", points: [
        "Exothermic reactions — release energy to surroundings; temperature rises (combustion, neutralisation)",
        "Endothermic reactions — absorb energy from surroundings; temperature falls (thermal decomposition)",
        "Bond breaking (endothermic) vs bond forming (exothermic)",
        "Bond energy calculations: ΔH = energy in (breaking bonds) – energy out (forming bonds)",
        "Reaction profiles — activation energy (Ea), energy of reactants/products, ΔH",
        "Required Practical 2 — temperature change in neutralisation/displacement",
        "H = mcΔT calorimetry calculations (q = mcΔT)",
        "Cells and batteries — chemical energy → electrical energy; simple cells",
        "Hydrogen fuel cells — H₂ + O₂ → water + electricity; advantages vs disadvantages",
      ]},
      { id: "ch6", topic: "Rate & Equilibrium ★ Paper 2", points: [
        "Rate of reaction — factors: concentration, temperature, surface area, catalysts, light (some)",
        "Rate = amount of reactant used (or product formed) ÷ time",
        "Calculating rate from a graph — gradient of tangent",
        "Collision theory — particles must collide with sufficient energy (activation energy)",
        "Effect of temperature — more particles have ≥ Ea; more successful collisions per second",
        "Effect of concentration/pressure — more particles in same volume → more collisions",
        "Effect of surface area — more collisions at surface; smaller particles = higher rate",
        "Catalysts — lower activation energy; provide alternative reaction pathway; not consumed",
        "Required Practical 3 — investigate rate of reaction (e.g. marble chips + HCl, thiosulfate + HCl)",
        "Reversible reactions — can go forwards and backwards (shown by ⇌)",
        "Dynamic equilibrium — forward rate = reverse rate; in a closed system",
        "Le Chatelier's principle — system opposes any imposed change",
        "Effect of temperature on equilibrium: increase → shifts away from exothermic side",
        "Effect of pressure on equilibrium: increase → shifts to side with fewer moles of gas",
        "Haber process — N₂ + 3H₂ ⇌ 2NH₃; 450°C, 200 atm, iron catalyst; compromise conditions",
        "Contact process — making sulfuric acid via SO₃ intermediate",
      ]},
      { id: "ch7", topic: "Organic Chemistry ★ Paper 2", points: [
        "Crude oil — mixture of hydrocarbons; separated by fractional distillation",
        "Fractions — LPG, petrol, kerosene, diesel, fuel oil, bitumen; different chain lengths",
        "Alkanes — general formula CₙH₂ₙ₊₂; saturated; complete and incomplete combustion",
        "Incomplete combustion — CO and soot (carbon) produced; health hazards",
        "Cracking — breaks long alkanes into shorter alkanes + alkenes; thermal or catalytic",
        "Alkenes — general formula CₙH₂ₙ; double C=C bond; unsaturated; test: decolourises bromine water",
        "Addition reactions of alkenes — with H₂, HBr, Br₂, H₂O (hydration → alcohol)",
        "Addition polymerisation — many alkene monomers → polymer; repeat unit",
        "Condensation polymerisation — monomers with two functional groups; e.g. nylon, polyester",
        "Alcohols — general formula CₙH₂ₙ₊₁OH; methanol, ethanol, propanol; uses and reactions",
        "Fermentation — glucose → ethanol + CO₂ (yeast, 25–35°C, anaerobic)",
        "Carboxylic acids — general formula CₙH₂ₙ₊₁COOH; weak acids; ethanoic acid in vinegar",
        "Esters — carboxylic acid + alcohol → ester + water (esterification; with acid catalyst)",
        "DNA — natural polymer made of nucleotide monomers; double helix",
        "Amino acids and proteins — condensation polymerisation; peptide bonds",
      ]},
      { id: "ch8", topic: "Chemical Analysis ★ Paper 2", points: [
        "Pure substances — single element or compound; sharp melting/boiling point",
        "Formulations — useful mixtures with specific properties (e.g. alloys, medicines, paint)",
        "Chromatography — separate mixtures by solubility; Rf = distance of spot ÷ distance of solvent front",
        "Required Practical 4 — investigate inks using paper chromatography",
        "Tests for gases: H₂ (squeaky pop), O₂ (relights glowing splint), CO₂ (limewater turns milky), Cl₂ (bleaches litmus)",
        "Flame tests — Li (red), Na (yellow), K (lilac/violet), Ca (orange-red), Cu (green/blue-green)",
        "NaOH(aq) test — metal hydroxides precipitate: Cu²⁺ (blue), Fe²⁺ (green), Fe³⁺ (brown), Al³⁺/Mg²⁺ (white, Al dissolves in excess)",
        "Tests for anions — halides (AgNO₃ solution), sulfates (BaCl₂ solution), carbonates (dilute HCl + limewater)",
        "Instrumental analysis — mass spectrometry (Mr and structure), IR spectroscopy (functional groups), NMR (structural),flame emission spectroscopy",
      ]},
      { id: "ch9", topic: "Chemistry of the Atmosphere ★ Paper 2", points: [
        "Modern atmosphere — N₂ (~78%), O₂ (~21%), Ar (~1%), CO₂ (~0.04%)",
        "Early atmosphere — mainly CO₂, water vapour; volcanic outgassing",
        "Oceans formed as water vapour condensed; CO₂ dissolved into oceans, locked in limestone/fossil fuels",
        "Photosynthesis released O₂ into the atmosphere over billions of years",
        "Greenhouse gases — CO₂, CH₄ (methane), water vapour; absorb and re-emit IR radiation",
        "Human activities increasing greenhouse gas levels — burning fossil fuels, deforestation, farming (CH₄ from livestock/rice paddies)",
        "Global climate change evidence — temperature records, ice cores, sea level rise, glacier retreat",
        "Effects of climate change — extreme weather, rising sea levels, biodiversity loss",
        "Carbon footprint — total CO₂ equivalent released by an individual, product or organisation",
        "Reducing carbon footprint — renewable energy, energy efficiency, carbon capture",
        "Atmospheric pollutants — CO (incomplete combustion, toxic), NOₓ (lightning/car engines, acid rain, photochemical smog), SO₂ (burning sulfur-containing fossil fuels, acid rain), soot/PM (respiratory harm)",
        "Acid rain — SO₂ + NOₓ + H₂O; damages buildings, harms aquatic life",
      ]},
      { id: "ch10", topic: "Using Resources ★ Paper 2", points: [
        "Finite (non-renewable) resources — e.g. crude oil, metal ores; will run out",
        "Renewable resources — e.g. plants, wind, solar; can be replenished",
        "Water treatment — filtration (remove solids), sedimentation, chlorination (kill pathogens), pH adjustment",
        "Desalination — removing salt from seawater; distillation or reverse osmosis",
        "Sewage treatment — screening, sedimentation, aerobic digestion (bacteria)",
        "Life cycle assessment (LCA) — evaluates environmental impact of a product from cradle to grave",
        "LCA stages — obtaining raw materials, manufacturing, use, disposal",
        "Reduce, reuse, recycle — decreasing resource use and waste",
        "Corrosion — rusting: Fe + O₂ + H₂O → hydrated iron(III) oxide; prevention: painting, galvanising, sacrificial anode",
        "Alloys — mixture of metals (and sometimes non-metals): steel, stainless steel, brass, bronze, solder",
        "Extracting metals using carbon — more common, cheaper; smelting",
        "Electrolysis of metals — used for reactive metals (Al) and for purification (Cu)",
        "Fertilisers — NPK; supply nitrogen, phosphorus, potassium; manufactured from Haber process (NH₃ → ammonium salts)",
        "Potable water vs pure water — potable is safe to drink but contains dissolved substances",
      ]},
    ],
  },

  // ── PHYSICS (AQA Triple) ──────────────────────────────────
  physics: {
    name: "Physics",
    board: "AQA Triple",
    color: "#f59e0b",
    icon: "⚛",
    exams: [
      { paper: "Paper 1 (Topics 1–4)", date: "2026-06-02", time: "AM" },
      { paper: "Paper 2 (Topics 5–8)", date: "2026-06-15", time: "AM" },
    ],
    topics: [
      { id: "ph1", topic: "Energy ★ Paper 1", points: [
        "Energy stores: kinetic, gravitational potential, elastic potential, thermal, chemical, nuclear, magnetic, electrostatic",
        "Energy transfers: mechanical work, heating, radiation, electrical",
        "Kinetic energy: Ek = ½mv²",
        "Gravitational potential energy: Ep = mgh",
        "Elastic potential energy: Ee = ½ke² (spring constant × extension²)",
        "Conservation of energy — energy cannot be created or destroyed",
        "Power: P = E/t and P = Fv (watts = joules per second)",
        "Efficiency = useful output energy ÷ total input energy (or useful power ÷ total power)",
        "Efficiency can never exceed 1 (100%)",
        "Reducing unwanted energy transfers — lubrication, insulation, streamlining",
        "Required Practical 1 — investigate specific heat capacity",
        "National Grid — step up (power station) and step down (homes) transformers",
        "Renewable energy sources — wind, solar, tidal, hydro, geothermal, biomass",
        "Non-renewable — coal, oil, gas, nuclear; reliability vs environmental impact",
      ]},
      { id: "ph2", topic: "Electricity ★ Paper 1", points: [
        "Electric current (I, amps) — rate of flow of charge; I = Q/t",
        "Potential difference (V, volts) — energy transferred per unit charge; V = W/Q",
        "Resistance (R, ohms) — opposition to current flow",
        "V = IR (Ohm's Law); ohmic conductors have constant R at constant temperature",
        "Required Practical 2 — I-V characteristics (resistor, lamp, diode)",
        "Non-ohmic: lamp (R increases as it gets hotter), diode (one-way current flow)",
        "Series circuits — same current everywhere; PDs add up; total R = R₁ + R₂",
        "Parallel circuits — same PD across each branch; currents add up; 1/R = 1/R₁ + 1/R₂",
        "Power: P = IV = I²R = V²/R",
        "Energy: E = QV = Pt (joules = coulombs × volts = watts × seconds)",
        "Mains electricity — AC (alternating current) at 230V, 50Hz in UK; DC is direct (battery)",
        "Domestic wiring — live (brown, 230V), neutral (blue, 0V), earth (green/yellow, safety)",
        "Fuses and circuit breakers — protect circuits from overload",
        "Static electricity — friction transfers electrons; like charges repel, unlike attract",
        "Electric fields — around charged objects; direction is from + to –",
      ]},
      { id: "ph3", topic: "Particle Model of Matter ★ Paper 1", points: [
        "Density: ρ = m/V (kg/m³ or g/cm³)",
        "Required Practical 3 — measure density of solid and liquid",
        "States of matter — solid (fixed shape/volume, vibrate), liquid (fixed volume, flow), gas (fill container)",
        "Particle arrangements and motion in each state",
        "Changes of state — melting, boiling, condensing, freezing, sublimation; physical changes",
        "Internal energy — total kinetic + potential energy of all particles",
        "Heating increases internal energy; during state change temperature stays constant",
        "Specific heat capacity: Q = mcΔT (J/kg°C)",
        "Specific latent heat: Q = mL; latent heat of fusion (melting) and vaporisation (boiling)",
        "Gas pressure — caused by collisions of particles with walls of container",
        "Boyle's Law: pV = constant (at constant temperature); p₁V₁ = p₂V₂",
        "Pressure and temperature: p/T = constant (at constant volume); absolute zero = –273°C = 0 K",
        "Kelvin scale: T(K) = T(°C) + 273",
      ]},
      { id: "ph4", topic: "Atomic Structure & Radioactivity ★ Paper 1", points: [
        "Structure of the atom — protons/neutrons in nucleus; electrons in shells",
        "Atoms are mostly empty space — radius ~10⁻¹⁰ m; nucleus ~10⁻¹⁵ m",
        "Isotopes — same element, different number of neutrons",
        "Development of atomic model — plum pudding → Rutherford scattering → Bohr model → quantum model",
        "Rutherford's gold foil experiment — alpha particles scattered; discovered nucleus",
        "Alpha (α): 2 protons + 2 neutrons (He nucleus); +2 charge; low penetration; highly ionising",
        "Beta (β⁻): electron emitted from nucleus; –1 charge; medium penetration; moderately ionising",
        "Gamma (γ): electromagnetic wave; no charge; very penetrating; weakly ionising",
        "Nuclear equations — conservation of mass number and atomic number",
        "Half-life — time for activity (or number of nuclei) to halve; calculations and graphs",
        "Background radiation — cosmic rays, radon gas, food, medical, nuclear industry",
        "Irradiation (exposed to radiation, can be shielded) vs contamination (radioactive material on/in body)",
        "Uses of nuclear radiation — medical tracers, cancer treatment, smoke detectors",
        "Nuclear fission — heavy nucleus splits into two (e.g. U-235 + neutron); chain reaction",
        "Nuclear fusion — two light nuclei join to form a heavier nucleus; releases more energy than fission; powers stars",
        "Nuclear reactors — controlled fission; coolant, control rods (absorb neutrons), moderator",
      ]},
      { id: "ph5", topic: "Forces ★ Paper 2", points: [
        "Contact forces: friction, tension, normal contact, air resistance",
        "Non-contact forces: gravity, electrostatic, magnetic",
        "Gravity: W = mg (weight in newtons; g = 9.8 N/kg on Earth)",
        "Resultant forces — vector sum of all forces; free-body diagrams",
        "Work done: W = Fs cosθ (simplified to W = Fs for force in direction of motion)",
        "Forces and elasticity — elastic deformation vs inelastic; F = ke (Hooke's Law)",
        "Required Practical 4 — investigate Hooke's Law (spring extension vs force)",
        "Moments: M = Fd; principle of moments for equilibrium",
        "Pressure in fluids: p = F/A; p = hρg for pressure at depth h",
        "Upthrust — equal to weight of fluid displaced (Archimedes' principle)",
        "Newton's 1st Law — object stays at rest or constant velocity unless acted on by a resultant force",
        "Newton's 2nd Law — F = ma (resultant force = mass × acceleration)",
        "Newton's 3rd Law — for every action, there is an equal and opposite reaction",
        "Momentum: p = mv; conservation of momentum (closed system)",
        "Impulse: force × time = change in momentum; F = Δ(mv)/Δt",
        "Stopping distance = thinking distance + braking distance",
        "Factors affecting braking distance: speed (kE), road/tyre condition, brakes",
        "Factors affecting thinking distance: speed, reaction time (drugs, alcohol, tiredness)",
        "Distance-time graphs — gradient = speed",
        "Velocity-time graphs — gradient = acceleration; area under graph = distance",
        "Equations of motion (SUVAT): v = u + at; s = ut + ½at²; v² = u² + 2as; s = ½(u+v)t",
        "Terminal velocity — drag force equals driving force; zero acceleration",
      ]},
      { id: "ph6", topic: "Waves ★ Paper 2", points: [
        "Transverse waves — oscillations perpendicular to direction of travel (light, water, EM)",
        "Longitudinal waves — oscillations parallel to direction of travel (sound); compressions and rarefactions",
        "Wave properties: amplitude, wavelength (λ), frequency (f), period (T)",
        "Wave equation: v = fλ (wave speed = frequency × wavelength)",
        "Required Practical 5 — measure speed of sound in air and/or ripple tank (water waves)",
        "Required Practical 6 — investigate reflection and refraction of light (ray box)",
        "Reflection — angle of incidence = angle of reflection (normal to surface)",
        "Refraction — change in wave speed at boundary; bends towards normal when slowing down",
        "Refractive index: n = sin(i)/sin(r) and n = c/v",
        "Total internal reflection — when angle of incidence > critical angle; used in optical fibres",
        "Electromagnetic (EM) spectrum — radio, microwave, IR, visible, UV, X-ray, gamma (all travel at 3×10⁸ m/s in vacuum)",
        "Uses and hazards of each EM wave: radio (comms), micro (comms/cooking), IR (heating), visible (sight/cameras), UV (tanning/vitamin D; skin cancer), X-ray (medical imaging; mutation), gamma (cancer treatment/sterilisation; mutation)",
        "Sound waves — compressions and rarefactions; travel through solids, liquids, gases; not in vacuum",
        "Ultrasound (>20 kHz) — medical scanning, sonar, cleaning; partial reflection at boundaries",
        "Seismic waves — P-waves (longitudinal, through liquid/solid), S-waves (transverse, not through liquid)",
        "Lenses — converging (convex) brings rays to a focus; real and virtual images",
        "Ray diagrams for converging lens — real inverted image (object outside F), virtual upright (inside F)",
      ]},
      { id: "ph7", topic: "Magnetism & Electromagnetism ★ Paper 2", points: [
        "Permanent magnets — north/south poles; always attract/repel (opposite/same poles)",
        "Induced (temporary) magnets — in magnetic field; always attract",
        "Magnetic field — invisible force field; shown by field lines from N to S outside magnet",
        "Plotting compass — aligns with field; use to map field patterns",
        "Electromagnetism — current-carrying conductor produces a magnetic field (right-hand grip rule for solenoid)",
        "Factors affecting electromagnet strength — current, number of turns, iron core",
        "The motor effect: force on a current in a magnetic field; F = BIl (B = flux density, I = current, l = length)",
        "Fleming's left-hand rule — thumb = force/motion, index = field, middle = current",
        "Electromagnetic induction — moving a conductor in a magnetic field induces a voltage (Faraday's law)",
        "Factors affecting induced EMF — speed of movement, strength of magnet, number of turns",
        "Generator effect — coil rotating in magnetic field induces AC; simple AC generator",
        "Transformers: Vp/Vs = Np/Ns; ideal transformer: VpIp = VsIs (conservation of energy)",
        "Step-up transformer — increases voltage, decreases current (for long-distance power transmission)",
        "Step-down transformer — decreases voltage, increases current (for safe household use)",
        "Loudspeakers — motor effect (AC current → alternating force on coil → vibrates cone)",
        "Microphones — generator effect (sound → vibrating coil in field → induces AC voltage)",
      ]},
      { id: "ph8", topic: "Space Physics ★ Paper 2", points: [
        "Life cycle of a star: nebula → protostar → main sequence (millions/billions of years) → red giant/supergiant → white dwarf/supernova/neutron star/black hole",
        "Main sequence — gravitational collapse balanced by radiation pressure from nuclear fusion",
        "Our Solar System — Sun, 8 planets, moons, asteroids, comets, dwarf planets",
        "Orbital motion — gravity provides centripetal force; v = 2πr/T",
        "Planets closer to Sun have higher orbital speed and shorter orbital period",
        "Light years — distance light travels in one year (9.46 × 10¹⁵ m)",
        "Red-shift — galaxies moving away from us; wavelength of light stretched; Hubble's observation",
        "Hubble's Law: v = Hd (recession speed ∝ distance)",
        "Big Bang theory — Universe started as extremely hot, dense point ~13.8 billion years ago; expanded and cooled",
        "Cosmic Microwave Background radiation — remnant heat from the Big Bang; evidence for Big Bang",
      ]},
    ],
  },

  // ── COMPUTER SCIENCE (OCR J277) ───────────────────────────
  computerScience: {
    name: "Computer Science",
    board: "OCR J277",
    color: "#06b6d4",
    icon: "💻",
    exams: [
      { paper: "Paper 1 (Systems)",  date: "2026-05-13", time: "PM" },
      { paper: "Paper 2 (Thinking)", date: "2026-05-19", time: "PM" },
    ],
    topics: [
      { id: "cs1", topic: "Systems Architecture", points: [
        "CPU components — ALU, CU, registers (PC, MAR, MDR, ACC)",
        "Von Neumann architecture",
        "Fetch-Decode-Execute cycle",
        "Factors affecting CPU performance — clock speed, cores, cache",
        "Embedded systems — examples and uses",
      ]},
      { id: "cs2", topic: "Memory & Storage", points: [
        "Primary storage — RAM, ROM, cache",
        "Secondary storage — HDD, SSD, optical, magnetic tape",
        "Virtual memory",
        "Units — bit, byte, KB, MB, GB, TB",
        "Data representation — binary, hexadecimal conversion",
        "Binary addition and overflow",
        "Two's complement — negative numbers",
        "Binary shifts — multiplication/division",
        "ASCII and Unicode",
        "Images — pixels, colour depth, resolution, file size",
        "Sound — sample rate, bit depth, file size",
        "Compression — lossy vs lossless, RLE",
      ]},
      { id: "cs3", topic: "Networks", points: [
        "Networks — LAN, WAN, PAN",
        "Client-server vs peer-to-peer",
        "Network topologies — star, bus, ring, mesh",
        "Transmission media — wired vs wireless",
        "Protocols — TCP/IP, HTTP, HTTPS, FTP, SMTP, DNS",
        "IP and MAC addresses",
        "Routers, switches, WAPs, NICs",
        "The internet — WWW, hosting, DNS",
        "Network security threats — malware types",
        "Mitigation — firewalls, encryption, two-factor auth",
      ]},
      { id: "cs4", topic: "Network Security", points: [
        "Social engineering — phishing, pharming, shouldering",
        "Malware — virus, worm, trojan, ransomware, spyware, adware",
        "SQL injection",
        "Brute force attacks",
        "Denial-of-service (DoS)",
        "Firewalls — packet filtering",
        "Encryption — symmetric vs asymmetric",
        "Penetration testing",
        "Cyber security roles",
      ]},
      { id: "cs5", topic: "Systems Software", points: [
        "Operating system functions",
        "Memory management",
        "Multitasking — scheduling",
        "Utility software — compression, defragmentation, antivirus, backup",
        "Device drivers",
        "Translators — compiler, interpreter, assembler",
      ]},
      { id: "cs6", topic: "Ethical & Legal", points: [
        "Ethical issues of computing",
        "Environmental impact",
        "Privacy — cookies, GDPR",
        "Copyright — patents, open source, Creative Commons",
        "Computer Misuse Act 1990",
        "Data Protection Act 2018",
        "Freedom of Information Act",
        "Stakeholder conflicts",
      ]},
      { id: "cs7", topic: "Algorithms", points: [
        "Computational thinking — abstraction, decomposition, pattern recognition",
        "Flowcharts and pseudocode",
        "Linear search — algorithm and trace",
        "Binary search — algorithm, trace, requirements",
        "Bubble sort — algorithm, trace, best/worst case",
        "Merge sort — algorithm, trace, efficiency",
        "Insertion sort — algorithm and trace",
        "Big-O notation — O(1), O(n), O(n^2), O(n log n)",
        "Decomposition and subroutines",
      ]},
      { id: "cs8", topic: "Programming", points: [
        "Variables, constants, data types",
        "Sequence, selection (if/elif/else), iteration (for/while)",
        "Arrays and lists",
        "String manipulation — length, slice, concatenation, upper/lower",
        "File handling — open, read, write, close",
        "Subroutines — procedures vs functions, parameters, return values",
        "Local vs global variables",
        "SQL — SELECT, FROM, WHERE, AND, OR",
        "SQL — INSERT, UPDATE",
        "Random number generation",
      ]},
      { id: "cs9", topic: "Boolean Logic", points: [
        "Logic gates — AND, OR, NOT, NAND, NOR, XOR",
        "Truth tables — construct and interpret",
        "Boolean expressions",
        "De Morgan's laws",
        "Simplifying Boolean algebra",
        "Half adder circuit",
      ]},
    ],
  },

  // ── ENGLISH LANGUAGE (AQA) ────────────────────────────────
  englishLang: {
    name: "English Language",
    board: "AQA",
    color: "#f43f5e",
    icon: "✍",
    exams: [
      { paper: "Paper 1 (Fiction)",     date: "2026-05-21", time: "AM" },
      { paper: "Paper 2 (Non-Fiction)", date: "2026-06-05", time: "AM" },
    ],
    topics: [
      { id: "el1", topic: "Reading Skills", points: [
        "Identifying explicit and implicit information",
        "Summarising and synthesising information",
        "Analysing writers methods — structure",
        "Analysing writers methods — language",
        "Evaluating effectiveness — reader response",
        "Comparing writers viewpoints",
        "Understanding purpose, audience, form (PAF)",
        "Identifying structural features — whole text level",
      ]},
      { id: "el2", topic: "Writing Skills", points: [
        "Writing for impact — narrative/descriptive",
        "Structural devices — cyclical, non-linear, shift in perspective",
        "Sentence forms for effect — fragments, minor sentences",
        "Paragraphing and discourse markers",
        "Vocabulary choices — connotation and register",
        "Rhetorical techniques — AFOREST",
        "Writing to argue, persuade, advise",
        "Audience-appropriate tone",
        "Proof-reading — spelling, punctuation, grammar (SPaG)",
      ]},
      { id: "el3", topic: "Language Analysis Techniques", points: [
        "Metaphor and simile",
        "Personification",
        "Pathetic fallacy",
        "Alliteration and sibilance",
        "Semantic field",
        "Connotation",
        "Tone and mood",
        "Imagery",
        "Repetition and listing",
        "Hyperbole",
      ]},
    ],
  },

  // ── ENGLISH LITERATURE (Edexcel) ──────────────────────────
  englishLit: {
    name: "English Literature",
    board: "Edexcel",
    color: "#ec4899",
    icon: "📖",
    exams: [
      { paper: "Paper 1 (Shakespeare/Drama)", date: "2026-05-11", time: "AM" },
      { paper: "Paper 2 (Novel/Poetry)",      date: "2026-05-19", time: "AM" },
    ],
    topics: [
      { id: "lit1", topic: "Romeo and Juliet (Shakespeare)", points: [
        "Plot — all 5 acts: prologue, meeting, balcony, marriage, banishment, tomb",
        "Romeo — impulsive love, transformation, fate",
        "Juliet — maturity, defiance of patriarchy, agency",
        "Friar Lawrence — well-meaning failure, role in tragedy",
        "The Nurse — comedy, loyalty, betrayal of Juliet",
        "Mercutio — wit, masculinity, catalyst for tragedy",
        "Lord and Lady Capulet — parental authority, patriarchal control",
        "Tybalt — hot-headed honour culture, foil to Romeo",
        "Theme: Love — romantic, courtly, familial",
        "Theme: Fate vs free will — star-crossed lovers",
        "Theme: Conflict — family, personal, social",
        "Theme: Youth vs age and impulsiveness",
        "Theme: Gender and patriarchy",
        "Theme: Death and the language of love/death",
        "Dramatic irony — audience knowledge vs character ignorance",
        "Key quotes — 12 essential quotations memorised",
        "Context: Elizabethan England — marriage, honour, religion",
        "Context: Source text — Brooke's Romeus and Juliet (1562)",
        "Form: Shakespearean tragedy — hamartia, catharsis",
        "Structure: Prologue as framing device; Act 3 as turning point",
      ]},
      { id: "lit2", topic: "An Inspector Calls (Priestley)", points: [
        "Plot — Inspector Goole's arrival, each family member's link to Eva Smith",
        "Arthur Birling — capitalism, complacency, wrong predictions",
        "Sybil Birling — class prejudice, denial, moral hypocrisy",
        "Sheila Birling — guilt, growth, socialist conscience",
        "Eric Birling — weakness, shame, hidden depths",
        "Gerald Croft — class and establishment, partial redemption",
        "Inspector Goole — socialist mouthpiece, mysterious identity, moral authority",
        "Eva Smith/Daisy Renton — symbol of working class, never seen",
        "Theme: Social responsibility — We are members of one body",
        "Theme: Class and inequality — Edwardian vs 1945 audience",
        "Theme: Gender — women as victims of male power",
        "Theme: Generational divide — older vs younger Birlings",
        "Theme: Guilt and responsibility — collective vs individual",
        "Theme: Time — 1912 setting, written 1945, staged 1946",
        "Dramatic devices — cliff-hangers, exits/entrances, the telephone",
        "Inspector as omniscient figure — who/what is he?",
        "Key quotes — 12 essential quotations memorised",
        "Context: Post-WW2 Britain — welfare state, Labour landslide 1945",
        "Context: Priestley's socialism — Time Plays influence",
        "Context: 1912 Edwardian era — Titanic, pre-WW1 complacency",
        "Form: Well-made play — unity of time, place, action",
        "Structure: Cyclic ending — the phone rings again",
      ]},
      { id: "lit3", topic: "Jekyll and Hyde (Stevenson)", points: [
        "Plot — Utterson's investigation, Hyde's crimes, Lanyon's shock, Jekyll's confession",
        "Dr Jekyll — respectability, repression, duality, self-destruction",
        "Mr Hyde — the id unleashed, violence, degeneration, freedom",
        "Utterson — rationalism, loyalty, Victorian gentleman narrator",
        "Dr Lanyon — rival, empirical science, dies of shock at seeing Hyde",
        "Theme: Duality of human nature — man is not truly one but truly two",
        "Theme: Repression and the Victorian self — respectability as prison",
        "Theme: Science vs religion — godlike experimentation",
        "Theme: Reputation and secrecy — gentlemen's code",
        "Theme: Evolution and degeneration — Hyde as primitive",
        "Theme: The city — London as labyrinth, fog, danger",
        "Narrative structure — multiple narrators, epistolary ending",
        "Gothic genre conventions — mystery, horror, the uncanny",
        "Key quotes — 10 essential quotations memorised",
        "Context: Victorian values — double life, hypocrisy, class",
        "Context: Darwin's evolution (1859) — fear of degeneration",
        "Context: Jack the Ripper (1888) — contemporary fears",
        "Context: Stevenson's own life — Edinburgh duality",
      ]},
      { id: "lit4", topic: "Conflict Poetry (Edexcel Cluster)", points: [
        "A Poison Tree (Blake) — repressed anger, revenge",
        "The Destruction of Sennacherib (Byron) — divine power, war's futility",
        "Extract from The Prelude (Wordsworth) — nature's sublime, guilt",
        "The Man He Killed (Hardy) — irony of war, ordinary men as enemies",
        "Cousin Kate (Rossetti) — gender, betrayal, class, shame",
        "Half-caste (Agard) — identity, racism, language as power",
        "Exposure (Owen) — WW1 futility, nature as enemy, waiting",
        "The Charge of the Light Brigade (Tennyson) — heroism, duty, tragedy",
        "Catrin (Clarke) — mother-daughter conflict, love and tension",
        "War Photographer (Satyamurti) — moral burden, distance, suffering",
        "Belfast Confetti (Carson) — conflict in everyday life, dislocation",
        "The Class Game (Casey) — class prejudice, identity, defiance",
        "Poppies (Weir) — maternal grief, home front, letting go",
        "No Problem (Zephaniah) — racism, identity, resilience",
        "What Were They Like? (Levertov) — Vietnam War, cultural destruction",
        "Comparing poems: structure and form — free verse vs ballad vs sonnet",
        "Comparing poems: voice — first person, dramatic monologue, third person",
        "Comparing poems: key themes — internal, political, war, social conflict",
        "Unseen poem technique — annotate, identify techniques, PEE",
        "Writing comparison essays — methods, structure, connectives",
      ]},
    ],
  },

  // ── HISTORY (Edexcel) ─────────────────────────────────────
  history: {
    name: "History",
    board: "Edexcel",
    color: "#a78bfa",
    icon: "🏛",
    exams: [
      { paper: "Paper 1 (Medicine)",              date: "2026-05-15", time: "AM" },
      { paper: "Paper 2 (Superpower & Elizabethan)", date: "2026-06-04", time: "AM" },
      { paper: "Paper 3 (Weimar & Nazi Germany)", date: "2026-06-09", time: "AM" },
    ],
    topics: [
      { id: "hi1", topic: "Medicine Through Time", points: [
        "Prehistoric medicine — natural and supernatural beliefs",
        "Ancient Egypt — written records, surgery, supernatural",
        "Ancient Greece — Hippocrates, four humours",
        "Ancient Rome — Galen, anatomy, public health (sewers, aqueducts)",
        "Medieval medicine — church, miasma, flagellants",
        "Black Death — causes believed and actual, responses",
        "Renaissance — Vesalius (anatomy), Harvey (circulation)",
        "17th-18th century — challenges to old ideas, hospitals",
        "Germ theory — Pasteur (1861), Koch (bacteria)",
        "Vaccination — Jenner (smallpox, 1796)",
        "Anaesthetics — Simpson (chloroform)",
        "Antiseptics — Lister (carbolic acid)",
        "Modern medicine — DNA, magic bullets, penicillin (Fleming)",
        "NHS — 1948, Beveridge Report",
        "Modern treatments — lifestyle, technology",
        "WW1 — trench medicine, blood banks, shell shock",
        "Source analysis skills — utility, reliability",
      ]},
      { id: "hi2", topic: "Cold War 1945-1991", points: [
        "Origins — ideological differences USA vs USSR",
        "Yalta and Potsdam conferences 1945",
        "Iron Curtain Speech — Churchill, 1946",
        "Truman Doctrine and Marshall Plan — 1947",
        "Berlin Blockade and Airlift 1948-49",
        "NATO and Warsaw Pact — formation",
        "Korean War 1950-53",
        "Hungarian Uprising 1956",
        "Berlin Crisis and Wall 1961",
        "Cuban Missile Crisis 1962 — causes, events, consequences",
        "Detente — SALT, Helsinki Accords",
        "Soviet invasion of Afghanistan 1979",
        "Reagan and Second Cold War",
        "Gorbachev — glasnost and perestroika",
        "Fall of Berlin Wall 1989",
        "Collapse of USSR 1991",
      ]},
      { id: "hi3", topic: "Elizabethan England", points: [
        "Elizabeth I — character, problems of 1558",
        "Religion — Middle Way, settlement of 1559",
        "Marriage question — suitors, impact",
        "Mary Queen of Scots — threat and execution",
        "Catholic threats — plots (Ridolfi, Throckmorton, Babington)",
        "Phillip II and Spain",
        "Spanish Armada 1588 — causes, events, consequences",
        "Poverty — causes, Elizabethan Poor Law",
        "Exploration — Drake, Raleigh, Virginia colony",
        "Entertainment — theatre, Shakespeare, Bear-baiting",
        "Elizabethan home life — houses, food, dress",
        "Source skills — usefulness and reliability",
      ]},
      { id: "hi4", topic: "Nazi Germany 1933-1939", points: [
        "Rise of Hitler — Weimar weaknesses, Great Depression",
        "Hitler becomes Chancellor 1933",
        "Reichstag Fire and Enabling Act 1933",
        "Night of the Long Knives 1934",
        "Hitler becomes Fuehrer 1934",
        "Totalitarian state — propaganda, censorship (Goebbels)",
        "SS and Gestapo — terror and control",
        "Opposition — resistance and conformity",
        "Youth movements — Hitler Youth, BDM",
        "Women — Kinder, Kueche, Kirche",
        "The economy — unemployment, rearmament, Four Year Plan",
        "Persecution of Jews — Nuremberg Laws 1935",
        "Kristallnacht 1938",
        "Life in Nazi Germany — church, education",
      ]},
    ],
  },

  // ── GERMAN (AQA) ──────────────────────────────────────────
  german: {
    name: "German",
    board: "AQA",
    color: "#f97316",
    icon: "🇩🇪",
    exams: [
      { paper: "Speaking (H)",  date: "2026-04-13", time: "AM" },
      { paper: "Listening (H)", date: "2026-05-07", time: "PM" },
      { paper: "Reading (H)",   date: "2026-05-14", time: "PM" },
      { paper: "Writing (H)",   date: "2026-06-01", time: "PM" },
    ],
    topics: [
      { id: "de1", topic: "Identity & Culture", points: [
        "Family — Meine Familie, Beziehungen",
        "Relationships and marriage — Ehe, Partnerschaft",
        "Friends — Freundschaft",
        "Social media and technology — Soziale Medien",
        "Free time — Freizeit, Hobbys",
        "Music, sport, TV — vocabulary",
        "Customs and festivals — Deutsche Feste",
        "Food and eating — deutsche Kueche",
      ]},
      { id: "de2", topic: "Local, National, Global", points: [
        "Home and town — Meine Stadt",
        "Environment — Umwelt, Klimawandel",
        "Local issues — Probleme in der Gesellschaft",
        "Travel and tourism — Reisen",
        "Germany — geography and regions",
        "Global issues — globale Probleme",
        "Healthy living — gesundes Leben",
        "Charitable work",
      ]},
      { id: "de3", topic: "Current & Future Study/Employment", points: [
        "School and subjects — Schule und Faecher",
        "School life — Schulleben",
        "Future plans — Zukunftsplaene",
        "Jobs and careers — Berufe",
        "Work experience — Arbeitspraktikum",
        "Applying for jobs",
        "Ambitions",
      ]},
      { id: "de4", topic: "Grammar", points: [
        "Nominative, accusative, dative, genitive cases",
        "Articles — der/die/das/ein/eine",
        "Adjective endings (all cases)",
        "Pronouns — personal, reflexive, relative",
        "Present tense — all verb types including sein/haben/werden",
        "Past tense — Perfekt (haben/sein + past participle)",
        "Imperfect — haben, sein, modal verbs",
        "Future tense — werden + infinitive",
        "Conditional — wuerden + infinitive",
        "Modal verbs — koennen, muessen, duerfen, sollen, wollen, moegen",
        "Word order — V2 rule, subordinate clauses (BWSDOW)",
        "Negation — nicht and kein",
        "Prepositions + cases — an, auf, in, mit, zu, nach, von",
        "Separable and inseparable verbs",
        "Comparative and superlative adjectives",
      ]},
    ],
  },

};

// ── EXAM DATES (flat list for calendar) ───────────────────
const ALL_EXAM_DATES = [];
Object.entries(GCSE_SUBJECTS).forEach(([key, subj]) => {
  subj.exams.forEach(exam => {
    ALL_EXAM_DATES.push({
      subject: subj.name,
      subjectKey: key,
      paper: exam.paper,
      date: exam.date,
      time: exam.time,
      color: subj.color,
      icon: subj.icon,
    });
  });
});
ALL_EXAM_DATES.sort((a, b) => a.date.localeCompare(b.date));

// ── STUDY PHASES ──────────────────────────────────────────
const STUDY_PHASES = [
  {
    name: "PHASE 1 — DEEP FOUNDATION",
    range: ["2026-03-01", "2026-04-03"],
    description: "Build all knowledge from scratch. One topic block per day. Read, make notes, retrieval.",
    color: "#3b82f6",
    dailyHours: 3,
    focus: "New learning + first retrieval pass",
    subjects: ["maths","physics","chemistry","biology","computerScience","englishLang","englishLit","german","history","furtherMaths"],
    atomicHabit: "2-minute rule: open the textbook. The rest follows.",
  },
  {
    name: "PHASE 2 — CONSOLIDATION",
    range: ["2026-04-04", "2026-04-24"],
    description: "Easter revision. Active recall — flashcards, practice questions, past papers by topic.",
    color: "#f59e0b",
    dailyHours: 5,
    focus: "Active recall + spaced repetition",
    subjects: ["maths","furtherMaths","physics","chemistry","biology","computerScience","history","german"],
    atomicHabit: "Never miss twice. If you skip a session, do half the next day.",
  },
  {
    name: "PHASE 3 — EXAM SIMULATION",
    range: ["2026-04-25", "2026-05-10"],
    description: "Full past papers under timed conditions. Mark with mark scheme immediately.",
    color: "#ef4444",
    dailyHours: 4,
    focus: "Past papers + targeted weak areas",
    subjects: ["biology","physics","chemistry","maths","englishLit","englishLang"],
    atomicHabit: "Identity: you are someone who does hard things consistently.",
  },
  {
    name: "PHASE 4 — EXAM PERIOD",
    range: ["2026-05-11", "2026-06-15"],
    description: "Exams running. Light revision on upcoming subject only. Sleep is revision.",
    color: "#10b981",
    dailyHours: 2,
    focus: "Targeted review of next exam only",
    subjects: [],
    atomicHabit: "Deep Work: 2x90-min sessions then full rest. No half-measures.",
  },
];

// ── DAILY RECOMMENDATION ENGINE ───────────────────────────
// Returns { phase, schedule, upcoming, daysUntilNext, next }
function getDailyRecommendation() {
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];

  const phase = STUDY_PHASES.find(p => todayStr >= p.range[0] && todayStr <= p.range[1])
    || STUDY_PHASES[STUDY_PHASES.length - 1];

  const upcoming = ALL_EXAM_DATES
    .filter(e => e.date >= todayStr)
    .sort((a, b) => a.date.localeCompare(b.date));

  const next = upcoming[0] || null;
  const daysUntilNext = next
    ? Math.ceil((new Date(next.date) - today) / 86400000)
    : null;

  const schedule = [];

  if (daysUntilNext !== null && daysUntilNext <= 3) {
    schedule.push({
      time: "Morning (90 min)",
      task: "FINAL REVIEW: " + next.subject + " — " + next.paper,
      type: "exam-prep",
      tip: "Practice questions only. No new content. Sleep early.",
    });
  } else {
    const dow = today.getDay();
    const rotation = [
      ["maths",          "history"],
      ["chemistry",      "biology"],
      ["computerScience","german"],
      ["englishLang",    "englishLit"],
      ["physics",        "furtherMaths"],
      ["maths",          "history"],
      ["biology",        "chemistry"],
    ];
    const todaySubjects = rotation[dow] || rotation[0];
    todaySubjects.forEach((sk, i) => {
      const subj = GCSE_SUBJECTS[sk];
      if (!subj) return;
      schedule.push({
        time: i === 0 ? "Morning (90 min deep work)" : "Afternoon (90 min deep work)",
        task: subj.icon + " " + subj.name,
        type: sk,
        tip: phase.focus,
        subject: subj,
      });
    });
  }

  return { phase, schedule, upcoming: upcoming.slice(0, 5), daysUntilNext, next };
}
