// ============================================================
// GCSE SPEC DATA — RAM'S EXAM COMMAND CENTER (FIXED 2026)
// Exam dates from Ram's verified timetable.
// Full spec content + correct getDailyRecommendation() for app.js.
// ============================================================

const GCSE_SUBJECTS = {

  // ── MATHS (Edexcel) ───────────────────────────────────────
  maths: {
    name: "Mathematics",
    board: "Edexcel",
    color: "#3b82f6",
    icon: "📐",
    exams: [
      { paper: "Paper 1 (Non-Calc)", date: "2026-05-14", time: "AM" },
      { paper: "Paper 2 (Calc)",     date: "2026-06-03", time: "AM" },
      { paper: "Paper 3 (Calc)",     date: "2026-06-10", time: "AM" },
    ],
    topics: [
      { id: "m1", topic: "Number", points: [
        "Integers, decimals, fractions — place value & ordering",
        "HCF, LCM, prime factorisation",
        "Powers, roots, surds",
        "Standard form (scientific notation)",
        "Percentages — increase/decrease, reverse, compound",
        "Ratio and proportion",
        "Bounds and error intervals",
      ]},
      { id: "m2", topic: "Algebra", points: [
        "Simplifying expressions & expanding brackets",
        "Factorising — common factor, difference of squares, quadratics",
        "Solving linear equations & inequalities",
        "Solving quadratics — factorising, formula, completing the square",
        "Simultaneous equations — substitution & elimination",
        "Sequences — nth term, arithmetic & geometric",
        "Functions — notation, composite, inverse",
        "Algebraic fractions",
        "Proof",
      ]},
      { id: "m3", topic: "Graphs", points: [
        "Coordinates and straight-line graphs (y=mx+c)",
        "Parallel & perpendicular lines",
        "Quadratic, cubic, reciprocal graphs",
        "Exponential and trigonometric graphs",
        "Transformations of graphs",
        "Real-life graphs — distance/time, velocity/time",
        "Gradient of a curve (tangent)",
        "Area under a graph",
      ]},
      { id: "m4", topic: "Ratio, Proportion & Rates", points: [
        "Direct and inverse proportion",
        "Speed, distance, time",
        "Density, mass, volume",
        "Exchange rates & best-buy problems",
        "Percentage problems — simple & compound interest",
      ]},
      { id: "m5", topic: "Geometry & Measures", points: [
        "Angles — parallel lines, polygons, bearings",
        "Properties of 2D shapes",
        "Circle theorems (all 8)",
        "Area and perimeter — all 2D shapes",
        "Volume and surface area — prisms, cylinders, spheres, cones, pyramids",
        "Pythagoras theorem",
        "Trigonometry — SOH CAH TOA, exact values",
        "Sine rule & cosine rule",
        "Vectors",
        "Loci and construction",
        "Congruence and similarity",
        "Transformations — reflection, rotation, translation, enlargement",
      ]},
      { id: "m6", topic: "Probability", points: [
        "Basic probability — scale, outcomes, equally likely",
        "Sample space diagrams & tree diagrams",
        "Venn diagrams",
        "Conditional probability",
        "Mutually exclusive & independent events",
        "Frequency trees",
      ]},
      { id: "m7", topic: "Statistics", points: [
        "Averages — mean, median, mode, range",
        "Frequency tables & grouped data",
        "Cumulative frequency & box plots",
        "Histograms — frequency density",
        "Scatter graphs — correlation, line of best fit",
        "Pie charts & bar charts",
        "Sampling methods",
      ]},
    ],
  },

  // ── FURTHER MATHS (AQA L2) ────────────────────────────────
  furtherMaths: {
    name: "Further Maths (L2)",
    board: "AQA",
    color: "#8b5cf6",
    icon: "∑",
    exams: [
      { paper: "Paper 1", date: "2026-06-08", time: "PM" },
      { paper: "Paper 2", date: "2026-06-15", time: "PM" },
    ],
    topics: [
      { id: "fm1", topic: "Number & Algebra", points: [
        "Factor theorem",
        "Algebraic long division",
        "Simplifying algebraic fractions — complex",
        "Completing the square — all forms",
        "Quadratic inequalities",
        "Simultaneous equations — one quadratic",
        "nth roots and fractional/negative indices",
        "Arithmetic & geometric series — notation",
      ]},
      { id: "fm2", topic: "Coordinate Geometry", points: [
        "Equation of a circle: (x-a)^2+(y-b)^2=r^2",
        "Intersection of a line and circle",
        "Tangent to a circle from a point",
        "Distance between two points in 3D",
      ]},
      { id: "fm3", topic: "Calculus", points: [
        "Differentiation — polynomials",
        "Gradient function, tangents & normals",
        "Stationary points — min/max classification",
        "Integration — polynomials",
        "Definite integration — area under a curve",
        "Area between two curves",
      ]},
      { id: "fm4", topic: "Matrix Algebra", points: [
        "Matrix addition, subtraction, multiplication",
        "2x2 determinant and inverse",
        "Matrix transformations — rotation, reflection, enlargement, shear",
        "Combining transformations using matrices",
        "Solving 2x2 simultaneous equations using matrices",
      ]},
      { id: "fm5", topic: "Trigonometry", points: [
        "Exact values: sin/cos/tan of 30, 45, 60 degrees",
        "Sine rule proof",
        "Cosine rule proof",
        "Area of a triangle = 0.5 ab sinC",
        "Solving trig equations in a given interval",
        "Trig identities: sin^2+cos^2=1, tan=sin/cos",
      ]},
      { id: "fm6", topic: "Functions & Graphs", points: [
        "Domain and range",
        "Inverse functions",
        "Composite functions",
        "Modulus function",
        "Graph transformations — all types",
      ]},
    ],
  },

  // ── BIOLOGY (AQA Triple) ──────────────────────────────────
  biology: {
    name: "Biology",
    board: "AQA Triple",
    color: "#84cc16",
    icon: "🧬",
    exams: [
      { paper: "Paper 1", date: "2026-05-12", time: "PM" },
      { paper: "Paper 2", date: "2026-06-08", time: "AM" },
    ],
    topics: [
      { id: "bio1", topic: "Cell Biology", points: [
        "Eukaryotic vs prokaryotic cells",
        "Animal and plant cell structures",
        "Cell specialisation — examples",
        "Microscopy — magnification formula",
        "Mitosis — stages and uses",
        "Stem cells — embryonic, adult, therapeutic cloning",
        "Diffusion, osmosis, active transport",
        "Required practical — osmosis in potato chips",
      ]},
      { id: "bio2", topic: "Organisation", points: [
        "Digestive system — organs and enzymes",
        "Enzymes — lock and key model, active site",
        "Effect of pH and temperature on enzymes",
        "Bile — emulsification",
        "Heart — chambers, valves, double circulatory system",
        "Blood vessels — arteries, veins, capillaries",
        "Blood components — RBC, WBC, platelets, plasma",
        "Plant organisation — leaves, stems, roots",
        "Transpiration and translocation",
        "Stomata and guard cells",
        "Cancer — benign vs malignant",
      ]},
      { id: "bio3", topic: "Infection & Response", points: [
        "Pathogens — bacteria, viruses, fungi, protists",
        "Communicable diseases — examples",
        "Defence systems — skin, mucus, lysozyme",
        "White blood cells — phagocytosis, antibodies, antitoxins",
        "Vaccination — herd immunity",
        "Antibiotics — how they work, resistance",
        "Drugs development — clinical trials",
        "Malaria, HIV, measles, salmonella, rose black spot",
      ]},
      { id: "bio4", topic: "Bioenergetics", points: [
        "Photosynthesis equation: 6CO2+6H2O to C6H12O6+6O2",
        "Rate of photosynthesis — limiting factors",
        "Required practical — effect of light on photosynthesis",
        "Uses of glucose in plants",
        "Aerobic respiration equation",
        "Anaerobic respiration — humans and yeast",
        "Response to exercise — heart rate, breathing rate",
        "Oxygen debt",
      ]},
      { id: "bio5", topic: "Homeostasis", points: [
        "Nervous system — neurones, synapse, reflex arc",
        "The brain — cerebral cortex, cerebellum, medulla",
        "The eye — structure and accommodation",
        "Hormones vs nervous system",
        "Endocrine system — glands and hormones",
        "Blood glucose regulation — insulin, glucagon",
        "Diabetes — Type 1 vs Type 2",
        "Water and ion balance — kidneys",
        "Urea production",
        "Dialysis and kidney transplant",
        "Menstrual cycle hormones — FSH, LH, oestrogen, progesterone",
        "Contraception and fertility treatments",
        "Thermoregulation — vasodilation, vasoconstriction, sweating",
      ]},
      { id: "bio6", topic: "Inheritance & Evolution", points: [
        "Meiosis vs mitosis",
        "DNA structure — double helix",
        "Genes, alleles, chromosomes",
        "Dominant and recessive — Punnett squares",
        "Sex determination: XX/XY",
        "Inherited disorders — cystic fibrosis, polydactyly",
        "Variation — genetic, environmental, combination",
        "Evolution — natural selection",
        "Evidence for evolution — fossils, antibiotic resistance",
        "Darwin vs Lamarck",
        "Speciation",
        "Genetic engineering — process and examples",
        "Cloning — tissue culture, embryo transplants",
      ]},
      { id: "bio7", topic: "Ecology", points: [
        "Ecosystems — biotic and abiotic factors",
        "Adaptations — structural, behavioural, functional",
        "Competition — intraspecific and interspecific",
        "Predator-prey cycles",
        "Feeding relationships — food chains, webs",
        "Biomass pyramids",
        "Decomposers and the carbon cycle",
        "The water cycle",
        "The nitrogen cycle",
        "Biodiversity — importance",
        "Human impacts — deforestation, climate change, pollution",
        "Conservation — maintained and managed ecosystems",
      ]},
    ],
  },

  // ── CHEMISTRY (AQA Triple) ────────────────────────────────
  chemistry: {
    name: "Chemistry",
    board: "AQA Triple",
    color: "#10b981",
    icon: "🧪",
    exams: [
      { paper: "Paper 1", date: "2026-05-18", time: "AM" },
      { paper: "Paper 2", date: "2026-06-12", time: "AM" },
    ],
    topics: [
      { id: "ch1", topic: "Atomic Structure & Periodic Table", points: [
        "Atomic structure — protons, neutrons, electrons",
        "Relative atomic mass and isotopes",
        "Electronic configurations (first 20 elements)",
        "Development of the periodic table — Mendeleev",
        "Periods and groups — trends",
        "Metals vs non-metals",
        "Group 1 — alkali metals: reactivity trend",
        "Group 7 — halogens: reactivity trend, displacement",
        "Group 0 — noble gases",
        "Transition metals — properties and uses",
      ]},
      { id: "ch2", topic: "Bonding, Structure & Properties", points: [
        "Ionic bonding — formation, giant lattice",
        "Covalent bonding — simple molecules",
        "Giant covalent structures — diamond, graphite, graphene, fullerenes",
        "Metallic bonding",
        "Properties — melting point, conductivity, solubility",
        "Polymer structures",
        "Nanoparticles — uses and risks",
      ]},
      { id: "ch3", topic: "Quantitative Chemistry", points: [
        "Relative formula mass (Mr)",
        "Moles: n = m/Mr",
        "Balanced equations and moles",
        "Concentration: c = n/V",
        "Percentage yield",
        "Atom economy",
        "Gas volumes (Avogadro's law)",
        "Titration calculations",
      ]},
      { id: "ch4", topic: "Chemical Changes", points: [
        "Reactivity series",
        "Extraction of metals — blast furnace, electrolysis",
        "Oxidation and reduction",
        "pH scale and neutralisation",
        "Acid + base, acid + metal, acid + carbonate reactions",
        "Electrolysis — products at electrodes",
        "Electrolysis of aqueous solutions",
        "Half equations",
      ]},
      { id: "ch5", topic: "Energy Changes", points: [
        "Exothermic and endothermic reactions",
        "Bond energies — calculating delta H",
        "H = mcDeltaT calorimetry",
        "Reaction profiles — activation energy",
        "Cells and batteries",
        "Fuel cells — hydrogen",
      ]},
      { id: "ch6", topic: "Rate & Equilibrium", points: [
        "Rate of reaction — factors",
        "Calculating rate from graphs",
        "Collision theory",
        "Catalysts — effect on activation energy",
        "Reversible reactions and Le Chatelier's principle",
        "Haber process — conditions and reasoning",
        "Contact process (sulfuric acid)",
      ]},
      { id: "ch7", topic: "Organic Chemistry", points: [
        "Crude oil — fractional distillation",
        "Alkanes — properties and combustion",
        "Cracking — thermal and catalytic",
        "Alkenes — double bond, addition reactions",
        "Polymers — addition and condensation",
        "Alcohols — fermentation, uses",
        "Carboxylic acids",
        "Esters — formation",
        "DNA and natural polymers",
      ]},
      { id: "ch8", topic: "Chemical Analysis", points: [
        "Pure substances and formulations",
        "Chromatography — Rf values",
        "Tests for gases: H2, O2, CO2, Cl2",
        "Flame tests — identifying metal ions",
        "NaOH test — identifying metal hydroxides",
        "Tests for halide and sulfate ions",
        "Instrumental analysis — spectroscopy",
      ]},
      { id: "ch9", topic: "Chemistry of the Atmosphere", points: [
        "Composition of the atmosphere",
        "Early atmosphere — volcanic outgassing",
        "Photosynthesis and oxygen",
        "Greenhouse gases and climate change",
        "Carbon footprint",
        "Atmospheric pollutants — sources and effects",
        "Acid rain",
      ]},
      { id: "ch10", topic: "Using Resources", points: [
        "Finite and renewable resources",
        "Water treatment",
        "Sewage treatment",
        "Life cycle assessment (LCA)",
        "Reduce, reuse, recycle",
        "Corrosion — rusting, prevention",
        "Alloys — steel, brass, bronze",
        "Fertilisers",
      ]},
    ],
  },

  // ── PHYSICS (AQA Triple) ──────────────────────────────────
  physics: {
    name: "Physics",
    board: "AQA Triple",
    color: "#f59e0b",
    icon: "⚛",
    exams: [
      { paper: "Paper 1", date: "2026-06-02", time: "AM" },
      { paper: "Paper 2", date: "2026-06-15", time: "AM" },
    ],
    topics: [
      { id: "ph1", topic: "Energy", points: [
        "Energy stores and transfers",
        "Kinetic energy: Ek = 0.5mv^2",
        "Gravitational potential energy: Ep = mgh",
        "Elastic potential energy: Ee = 0.5ke^2",
        "Conservation of energy",
        "Power: P = E/t = Fv",
        "Efficiency = useful output / total input",
        "National grid and energy transfer",
        "Reducing unwanted energy transfers",
        "Renewable and non-renewable energy sources",
      ]},
      { id: "ph2", topic: "Electricity", points: [
        "Current, potential difference, resistance",
        "V = IR (Ohm's Law)",
        "Series and parallel circuits",
        "Resistors — I-V characteristics",
        "Power: P = IV = I^2 R = V^2/R",
        "Energy: E = QV = Pt",
        "Mains electricity — AC vs DC",
        "Domestic appliances and wiring",
        "National grid and transformers",
        "Static electricity",
      ]},
      { id: "ph3", topic: "Particle Model", points: [
        "Density: rho = m/V",
        "States of matter — particle arrangements",
        "Internal energy — heating",
        "Specific heat capacity: Q = mcDeltaT",
        "Specific latent heat: Q = mL",
        "Pressure in gases — pV = constant (Boyle's Law)",
        "Temperature and pressure — absolute zero",
      ]},
      { id: "ph4", topic: "Atomic Structure", points: [
        "Structure of the atom — nucleus, electrons",
        "Isotopes and relative atomic mass",
        "Alpha, beta, gamma radiation — properties",
        "Nuclear equations",
        "Half-life calculations",
        "Background radiation",
        "Irradiation vs contamination",
        "Nuclear fission and chain reactions",
        "Nuclear fusion",
      ]},
      { id: "ph5", topic: "Forces", points: [
        "Contact and non-contact forces",
        "Gravity: W = mg",
        "Resultant forces and free-body diagrams",
        "Work done: W = Fs",
        "Forces and elasticity: F = ke",
        "Moments: M = Fd",
        "Pressure: p = F/A",
        "Newton's Laws of Motion",
        "Momentum: p = mv; conservation",
        "Stopping distance — thinking, braking, total",
        "Speed-time and distance-time graphs",
        "SUVAT equations",
      ]},
      { id: "ph6", topic: "Waves", points: [
        "Transverse vs longitudinal waves",
        "Wave equation: v = f x lambda",
        "Reflection, refraction, absorption",
        "Electromagnetic spectrum — all 7 types",
        "Radio, microwave, IR, visible, UV, X-ray, gamma — uses and hazards",
        "Sound waves — compression, rarefaction",
        "Ultrasound — medical uses",
        "Seismic waves — P and S waves",
        "Lenses — converging, real and virtual images",
      ]},
      { id: "ph7", topic: "Magnetism & Electromagnetism", points: [
        "Permanent and induced magnets",
        "Magnetic field patterns",
        "Electromagnetism — solenoid",
        "The motor effect: F = BIl",
        "Fleming's left-hand rule",
        "Electromagnetic induction",
        "Generator effect",
        "Transformers: Vp/Vs = Np/Ns",
        "Loudspeakers and microphones",
      ]},
      { id: "ph8", topic: "Space Physics", points: [
        "Life cycle of a star",
        "The Solar System",
        "Red-shift and expanding universe",
        "Big Bang theory",
        "Orbital motion",
      ]},
    ],
  },

  // ── COMPUTER SCIENCE (OCR J277) ───────────────────────────
  computerScience: {
    name: "Computer Science",
    board: "OCR J277",
    color: "#06b6d4",
    icon: "💻",
    exams: [
      { paper: "Paper 1 (Systems)",  date: "2026-05-13", time: "PM" },
      { paper: "Paper 2 (Thinking)", date: "2026-05-19", time: "PM" },
    ],
    topics: [
      { id: "cs1", topic: "Systems Architecture", points: [
        "CPU components — ALU, CU, registers (PC, MAR, MDR, ACC)",
        "Von Neumann architecture",
        "Fetch-Decode-Execute cycle",
        "Factors affecting CPU performance — clock speed, cores, cache",
        "Embedded systems — examples and uses",
      ]},
      { id: "cs2", topic: "Memory & Storage", points: [
        "Primary storage — RAM, ROM, cache",
        "Secondary storage — HDD, SSD, optical, magnetic tape",
        "Virtual memory",
        "Units — bit, byte, KB, MB, GB, TB",
        "Data representation — binary, hexadecimal conversion",
        "Binary addition and overflow",
        "Two's complement — negative numbers",
        "Binary shifts — multiplication/division",
        "ASCII and Unicode",
        "Images — pixels, colour depth, resolution, file size",
        "Sound — sample rate, bit depth, file size",
        "Compression — lossy vs lossless, RLE",
      ]},
      { id: "cs3", topic: "Networks", points: [
        "Networks — LAN, WAN, PAN",
        "Client-server vs peer-to-peer",
        "Network topologies — star, bus, ring, mesh",
        "Transmission media — wired vs wireless",
        "Protocols — TCP/IP, HTTP, HTTPS, FTP, SMTP, DNS",
        "IP and MAC addresses",
        "Routers, switches, WAPs, NICs",
        "The internet — WWW, hosting, DNS",
        "Network security threats — malware types",
        "Mitigation — firewalls, enc
